//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Live
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    
    public partial class CompanyPurchase : INotifyPropertyChanged
    {
        public CompanyPurchase()
        {
            this.PurchaseTypes = new ObservableCollection<PurchaseType>();
        }
    
        private int _Id;
        public int Id
        {
            get { return _Id; }
            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private string _Quantity;
        public string Quantity
        {
            get { return _Quantity; }
            set
            {
                if (_Quantity != value)
                {
                    _Quantity = value;
                    OnPropertyChanged("Quantity");
                }
            }
        }
        private string _Date;
        public string Date
        {
            get { return _Date; }
            set
            {
                if (_Date != value)
                {
                    _Date = value;
                    OnPropertyChanged("Date");
                }
            }
        }
        private string _Description;
        public string Description
        {
            get { return _Description; }
            set
            {
                if (_Description != value)
                {
                    _Description = value;
                    OnPropertyChanged("Description");
                }
            }
        }
        private string _Amount;
        public string Amount
        {
            get { return _Amount; }
            set
            {
                if (_Amount != value)
                {
                    _Amount = value;
                    OnPropertyChanged("Amount");
                }
            }
        }
        private int _BilansId;
        public int BilansId
        {
            get { return _BilansId; }
            set
            {
                if (_BilansId != value)
                {
                    _BilansId = value;
                    OnPropertyChanged("BilansId");
                }
            }
        }
    
        private ObservableCollection<PurchaseType> _PurchaseTypes;
        public ObservableCollection<PurchaseType> PurchaseTypes
        {
            get { return _PurchaseTypes; }
            set
            {
                if (_PurchaseTypes != value)
                {
                    _PurchaseTypes = value;
                    OnPropertyChanged("PurchaseTypes");
                }
            }
        }
        private Bilans _Bilan;
        public Bilans Bilan
        {
            get { return _Bilan; }
            set
            {
                if (_Bilan != value)
                {
                    _Bilan = value;
                    OnPropertyChanged("Bilan");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
