//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Live
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LiveModelContainer : DbContext
    {
        public LiveModelContainer()
            : base("name=LiveModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<WeedSale> WeedSales { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<Strain> Strains { get; set; }
        public virtual DbSet<CompanyPurchase> CompanyPurchases { get; set; }
        public virtual DbSet<PurchaseType> PurchaseTypes { get; set; }
        public virtual DbSet<CapitalInvestment> CapitalInvestments { get; set; }
        public virtual DbSet<Salary> Salaries { get; set; }
        public virtual DbSet<Bilans> Bilans { get; set; }
    }
}
