//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Live
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    
    public partial class PurchaseType : INotifyPropertyChanged
    {
        private int _Id;
        public int Id
        {
            get { return _Id; }
            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private string _PurchaseName;
        public string PurchaseName
        {
            get { return _PurchaseName; }
            set
            {
                if (_PurchaseName != value)
                {
                    _PurchaseName = value;
                    OnPropertyChanged("PurchaseName");
                }
            }
        }
        private int _CompanyPurchaseId;
        public int CompanyPurchaseId
        {
            get { return _CompanyPurchaseId; }
            set
            {
                if (_CompanyPurchaseId != value)
                {
                    _CompanyPurchaseId = value;
                    OnPropertyChanged("CompanyPurchaseId");
                }
            }
        }
    
        private CompanyPurchase _CompanyPurchase;
        public CompanyPurchase CompanyPurchase
        {
            get { return _CompanyPurchase; }
            set
            {
                if (_CompanyPurchase != value)
                {
                    _CompanyPurchase = value;
                    OnPropertyChanged("CompanyPurchase");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
