//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Live
{
    using System;
    using System.Collections.Generic;
    using System.Collections.ObjectModel;
    using System.ComponentModel;
    
    public partial class WeedSale : INotifyPropertyChanged
    {
        private int _Id;
        public int Id
        {
            get { return _Id; }
            set
            {
                if (_Id != value)
                {
                    _Id = value;
                    OnPropertyChanged("Id");
                }
            }
        }
        private string _Qunatity;
        public string Qunatity
        {
            get { return _Qunatity; }
            set
            {
                if (_Qunatity != value)
                {
                    _Qunatity = value;
                    OnPropertyChanged("Qunatity");
                }
            }
        }
        private string _Date;
        public string Date
        {
            get { return _Date; }
            set
            {
                if (_Date != value)
                {
                    _Date = value;
                    OnPropertyChanged("Date");
                }
            }
        }
        private int _CustomerId;
        public int CustomerId
        {
            get { return _CustomerId; }
            set
            {
                if (_CustomerId != value)
                {
                    _CustomerId = value;
                    OnPropertyChanged("CustomerId");
                }
            }
        }
        private Nullable<int> _StrainId;
        public Nullable<int> StrainId
        {
            get { return _StrainId; }
            set
            {
                if (_StrainId != value)
                {
                    _StrainId = value;
                    OnPropertyChanged("StrainId");
                }
            }
        }
        private int _BilansId;
        public int BilansId
        {
            get { return _BilansId; }
            set
            {
                if (_BilansId != value)
                {
                    _BilansId = value;
                    OnPropertyChanged("BilansId");
                }
            }
        }
    
        private Customer _Customer;
        public Customer Customer
        {
            get { return _Customer; }
            set
            {
                if (_Customer != value)
                {
                    _Customer = value;
                    OnPropertyChanged("Customer");
                }
            }
        }
        private Strain _Strain;
        public Strain Strain
        {
            get { return _Strain; }
            set
            {
                if (_Strain != value)
                {
                    _Strain = value;
                    OnPropertyChanged("Strain");
                }
            }
        }
        private Bilans _Bilan;
        public Bilans Bilan
        {
            get { return _Bilan; }
            set
            {
                if (_Bilan != value)
                {
                    _Bilan = value;
                    OnPropertyChanged("Bilan");
                }
            }
        }
    
        #region INotifyPropertyChanged Members
        public event PropertyChangedEventHandler PropertyChanged;
    
        protected void OnPropertyChanged(string propertyName)
        {
            OnPropertyChanged(new PropertyChangedEventArgs(propertyName));
        }
    
        protected virtual void OnPropertyChanged(PropertyChangedEventArgs e)
        {
            if (PropertyChanged != null)
                PropertyChanged(this, e);
        }
        #endregion
    }
}
